<?php

/**
 * BaseStudent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $first_name
 * @property varchar $middle_name
 * @property varchar $last_name
 * @property varchar $email
 * @property varchar $password
 * @property integer $section_id
 * @property boolean $is_active
 * @property Doctrine_Collection $sections
 * @property Doctrine_Collection $exam_results
 * 
 * @method varchar             getFirstName()    Returns the current record's "first_name" value
 * @method varchar             getMiddleName()   Returns the current record's "middle_name" value
 * @method varchar             getLastName()     Returns the current record's "last_name" value
 * @method varchar             getEmail()        Returns the current record's "email" value
 * @method varchar             getPassword()     Returns the current record's "password" value
 * @method integer             getSectionId()    Returns the current record's "section_id" value
 * @method boolean             getIsActive()     Returns the current record's "is_active" value
 * @method Doctrine_Collection getSections()     Returns the current record's "sections" collection
 * @method Doctrine_Collection getExamResults()  Returns the current record's "exam_results" collection
 * @method Student             setFirstName()    Sets the current record's "first_name" value
 * @method Student             setMiddleName()   Sets the current record's "middle_name" value
 * @method Student             setLastName()     Sets the current record's "last_name" value
 * @method Student             setEmail()        Sets the current record's "email" value
 * @method Student             setPassword()     Sets the current record's "password" value
 * @method Student             setSectionId()    Sets the current record's "section_id" value
 * @method Student             setIsActive()     Sets the current record's "is_active" value
 * @method Student             setSections()     Sets the current record's "sections" collection
 * @method Student             setExamResults()  Sets the current record's "exam_results" collection
 * 
 * @package    devcup2014
 * @subpackage model
 * @author     kncapara@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('students');
        $this->hasColumn('first_name', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('middle_name', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('last_name', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('email', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('password', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             ));


        $this->index('first_name', array(
             'fields' => 
             array(
              0 => 'first_name',
             ),
             ));
        $this->index('middle_name', array(
             'fields' => 
             array(
              0 => 'middle_name',
             ),
             ));
        $this->index('last_name', array(
             'fields' => 
             array(
              0 => 'last_name',
             ),
             ));
        $this->index('email', array(
             'fields' => 
             array(
              0 => 'email',
             ),
             ));
        $this->index('is_active', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Section as sections', array(
             'refClass' => 'StudentSection',
             'local' => 'student_id',
             'foreign' => 'section_id'));

        $this->hasMany('ExamResult as exam_results', array(
             'local' => 'id',
             'foreign' => 'student_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}