<?php

/**
 * BaseStudentSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $student_id
 * @property integer $section_id
 * 
 * @method integer        getStudentId()  Returns the current record's "student_id" value
 * @method integer        getSectionId()  Returns the current record's "section_id" value
 * @method StudentSection setStudentId()  Sets the current record's "student_id" value
 * @method StudentSection setSectionId()  Sets the current record's "section_id" value
 * 
 * @package    devcup2014
 * @subpackage model
 * @author     kncapara@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStudentSection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('student_section');
        $this->hasColumn('student_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}