<?php

/**
 * BaseExam
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $profile_id
 * @property Profile $profile
 * @property Doctrine_Collection $id
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getProfileId()  Returns the current record's "profile_id" value
 * @method Profile             getProfile()    Returns the current record's "profile" value
 * @method Doctrine_Collection getId()         Returns the current record's "id" collection
 * @method Exam                setName()       Sets the current record's "name" value
 * @method Exam                setProfileId()  Sets the current record's "profile_id" value
 * @method Exam                setProfile()    Sets the current record's "profile" value
 * @method Exam                setId()         Sets the current record's "id" collection
 * 
 * @package    devcup2014
 * @subpackage model
 * @author     kncapara@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseExam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('exams');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('profile_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile as profile', array(
             'local' => 'profile_id',
             'foreign' => 'id'));

        $this->hasMany('Question as id', array(
             'local' => 'id',
             'foreign' => 'exam_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}