<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $type
 * @property varchar $first_name
 * @property varchar $middle_name
 * @property varchar $last_name
 * @property varchar $email
 * @property varchar $password
 * @property integer $section_id
 * @property boolean $is_active
 * @property varchar $email_token
 * @property Section $section
 * @property Doctrine_Collection $exams
 * 
 * @method varchar             getType()        Returns the current record's "type" value
 * @method varchar             getFirstName()   Returns the current record's "first_name" value
 * @method varchar             getMiddleName()  Returns the current record's "middle_name" value
 * @method varchar             getLastName()    Returns the current record's "last_name" value
 * @method varchar             getEmail()       Returns the current record's "email" value
 * @method varchar             getPassword()    Returns the current record's "password" value
 * @method integer             getSectionId()   Returns the current record's "section_id" value
 * @method boolean             getIsActive()    Returns the current record's "is_active" value
 * @method varchar             getEmailToken()  Returns the current record's "email_token" value
 * @method Section             getSection()     Returns the current record's "section" value
 * @method Doctrine_Collection getExams()       Returns the current record's "exams" collection
 * @method Profile             setType()        Sets the current record's "type" value
 * @method Profile             setFirstName()   Sets the current record's "first_name" value
 * @method Profile             setMiddleName()  Sets the current record's "middle_name" value
 * @method Profile             setLastName()    Sets the current record's "last_name" value
 * @method Profile             setEmail()       Sets the current record's "email" value
 * @method Profile             setPassword()    Sets the current record's "password" value
 * @method Profile             setSectionId()   Sets the current record's "section_id" value
 * @method Profile             setIsActive()    Sets the current record's "is_active" value
 * @method Profile             setEmailToken()  Sets the current record's "email_token" value
 * @method Profile             setSection()     Sets the current record's "section" value
 * @method Profile             setExams()       Sets the current record's "exams" collection
 * 
 * @package    devcup2014
 * @subpackage model
 * @author     kncapara@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profiles');
        $this->hasColumn('type', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('first_name', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('middle_name', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('last_name', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('email', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('password', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('email_token', 'varchar', 50, array(
             'type' => 'varchar',
             'length' => 50,
             ));


        $this->index('type', array(
             'fields' => 
             array(
              0 => 'type',
             ),
             ));
        $this->index('first_name', array(
             'fields' => 
             array(
              0 => 'first_name',
             ),
             ));
        $this->index('middle_name', array(
             'fields' => 
             array(
              0 => 'middle_name',
             ),
             ));
        $this->index('last_name', array(
             'fields' => 
             array(
              0 => 'last_name',
             ),
             ));
        $this->index('email', array(
             'fields' => 
             array(
              0 => 'email',
             ),
             ));
        $this->index('email_token', array(
             'fields' => 
             array(
              0 => 'email_token',
             ),
             ));
        $this->index('is_active', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section as section', array(
             'local' => 'section_id',
             'foreign' => 'id'));

        $this->hasMany('Exam as exams', array(
             'local' => 'id',
             'foreign' => 'profile_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}