<?php

/**
 * ExamResultTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamResultTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamResultTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExamResult');
    }
}