<?php

/**
 * ExamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Exam');
    }
}