<?php

/**
 * Profile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    devcup2014
 * @subpackage model
 * @author     kncapara@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Profile extends BaseProfile
{
  const
    TYPE_TEACHER = 'teacher',
    TYPE_STUDENT = 'student';

  /**
   * Short Description here.
   *
   * @author Kenn Capara
   * @return void
   */
  public function preInsert($event)
  {
    $this
      ->setIsActive(false)
      ->setEmailToken($this->generateEmailToken())
      ;

    return $this;
  }

  /**
   * Short Description here.
   *
   * @author Kenn Capara
   * @return void
   */
  public function generateEmailToken()
  {
    $crypt = new RandomGenerator;
    return $crypt->setToken(sfConfig::get('app_random_token'))->getCrypt();
  }
}
