<?php

/**
 * StudentSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    devcup2014
 * @subpackage model
 * @author     kncapara@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class StudentSection extends BaseStudentSection
{
}
