<?php

/**
 * StudentSectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StudentSectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StudentSectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StudentSection');
    }
}