<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version13 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('exams', 'active_at', 'timestamp', '25', array(
             ));
        $this->addColumn('exams', 'end_at', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('exams', 'active_at');
        $this->removeColumn('exams', 'end_at');
    }
}