<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addprofiles extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('profiles', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'type' => 
             array(
              'type' => 'varchar',
              'length' => 50,
             ),
             'first_name' => 
             array(
              'type' => 'varchar',
              'length' => 50,
             ),
             'middle_name' => 
             array(
              'type' => 'varchar',
              'length' => 50,
             ),
             'last_name' => 
             array(
              'type' => 'varchar',
              'length' => 50,
             ),
             'email' => 
             array(
              'type' => 'varchar',
              'length' => 50,
             ),
             'password' => 
             array(
              'type' => 'varchar',
              'length' => 50,
             ),
             'status' => 
             array(
              'type' => 'varchar',
              'length' => 50,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
              'type' => 
              array(
              'fields' => 
              array(
               0 => 'type',
              ),
              ),
              'first_name' => 
              array(
              'fields' => 
              array(
               0 => 'first_name',
              ),
              ),
              'middle_name' => 
              array(
              'fields' => 
              array(
               0 => 'middle_name',
              ),
              ),
              'last_name' => 
              array(
              'fields' => 
              array(
               0 => 'last_name',
              ),
              ),
              'email' => 
              array(
              'fields' => 
              array(
               0 => 'email',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('profiles');
    }
}