<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('answers', 'profile_id');
        $this->addColumn('answers', 'student_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('answers', 'profile_id', 'integer', '8', array(
             ));
        $this->removeColumn('answers', 'student_id');
    }
}