<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version12 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('answers', 'answers_profile_id_profiles_id', array(
             'name' => 'answers_profile_id_profiles_id',
             'local' => 'profile_id',
             'foreign' => 'id',
             'foreignTable' => 'profiles',
             ));
        $this->createForeignKey('answers', 'answers_question_id_questions_id', array(
             'name' => 'answers_question_id_questions_id',
             'local' => 'question_id',
             'foreign' => 'id',
             'foreignTable' => 'questions',
             ));
        $this->addIndex('answers', 'answers_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->addIndex('answers', 'answers_question_id', array(
             'fields' => 
             array(
              0 => 'question_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('answers', 'answers_profile_id_profiles_id');
        $this->dropForeignKey('answers', 'answers_question_id_questions_id');
        $this->removeIndex('answers', 'answers_profile_id', array(
             'fields' => 
             array(
              0 => 'profile_id',
             ),
             ));
        $this->removeIndex('answers', 'answers_question_id', array(
             'fields' => 
             array(
              0 => 'question_id',
             ),
             ));
    }
}