<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version15 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('student_section', 'student_section_section_id_sections_id', array(
             'name' => 'student_section_section_id_sections_id',
             'local' => 'section_id',
             'foreign' => 'id',
             'foreignTable' => 'sections',
             ));
        $this->createForeignKey('student_section', 'student_section_student_id_students_id', array(
             'name' => 'student_section_student_id_students_id',
             'local' => 'student_id',
             'foreign' => 'id',
             'foreignTable' => 'students',
             ));
        $this->addIndex('student_section', 'student_section_section_id', array(
             'fields' => 
             array(
              0 => 'section_id',
             ),
             ));
        $this->addIndex('student_section', 'student_section_student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('student_section', 'student_section_section_id_sections_id');
        $this->dropForeignKey('student_section', 'student_section_student_id_students_id');
        $this->removeIndex('student_section', 'student_section_section_id', array(
             'fields' => 
             array(
              0 => 'section_id',
             ),
             ));
        $this->removeIndex('student_section', 'student_section_student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
    }
}