<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('profiles', 'email_token', 'varchar', '50', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('profiles', 'email_token');
    }
}