<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version17 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('exam_results', 'exam_results_student_id_students_id', array(
             'name' => 'exam_results_student_id_students_id',
             'local' => 'student_id',
             'foreign' => 'id',
             'foreignTable' => 'students',
             ));
        $this->createForeignKey('exam_results', 'exam_results_exam_id_exams_id', array(
             'name' => 'exam_results_exam_id_exams_id',
             'local' => 'exam_id',
             'foreign' => 'id',
             'foreignTable' => 'exams',
             ));
        $this->addIndex('exam_results', 'exam_results_student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
        $this->addIndex('exam_results', 'exam_results_exam_id', array(
             'fields' => 
             array(
              0 => 'exam_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('exam_results', 'exam_results_student_id_students_id');
        $this->dropForeignKey('exam_results', 'exam_results_exam_id_exams_id');
        $this->removeIndex('exam_results', 'exam_results_student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
        $this->removeIndex('exam_results', 'exam_results_exam_id', array(
             'fields' => 
             array(
              0 => 'exam_id',
             ),
             ));
    }
}