<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version23 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('subjects', 'section_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('subjects', 'section_id');
    }
}