<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version8 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('profiles', 'status');
        $this->addColumn('profiles', 'is_active', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->addColumn('profiles', 'status', 'varchar', '50', array(
             ));
        $this->removeColumn('profiles', 'is_active');
    }
}