<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version16 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('exam_results', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'student_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'exam_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'correct_count' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'question_count' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'score' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('exam_results');
    }
}