<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('answers', 'answers_student_id_students_id', array(
             'name' => 'answers_student_id_students_id',
             'local' => 'student_id',
             'foreign' => 'id',
             'foreignTable' => 'students',
             ));
        $this->addIndex('answers', 'answers_student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('answers', 'answers_student_id_students_id');
        $this->removeIndex('answers', 'answers_student_id', array(
             'fields' => 
             array(
              0 => 'student_id',
             ),
             ));
    }
}