<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('profiles', 'profiles_section_id_sections_id', array(
             'name' => 'profiles_section_id_sections_id',
             'local' => 'section_id',
             'foreign' => 'id',
             'foreignTable' => 'sections',
             ));
        $this->addIndex('profiles', 'profiles_section_id', array(
             'fields' => 
             array(
              0 => 'section_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('profiles', 'profiles_section_id_sections_id');
        $this->removeIndex('profiles', 'profiles_section_id', array(
             'fields' => 
             array(
              0 => 'section_id',
             ),
             ));
    }
}