<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/08/16 12:20:33

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=devcup2014',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
