<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/08/16 13:29:19
sfConfig::add(array(
  'app_random_token' => 'daisonphillipkenn',
  'app_email_noreply' => 'devcup2014noreply@gmail.com',
));
