Answer:
  tableName: 'answers'
  columns:
    student_id: integer
    question_id: integer
    answer: string(50)

  indexes:
    answer: 
      fields: [answer]

  relations:
    Student:
      alias: student
      foreignAlias: answers
    Question:
      alias: question
      foreignAlias: question_id

  actAs:
    - Timestampable
