Profile:
  tableName: 'profiles'
  columns:
    # Teacher, Student
    type: varchar(50)

    first_name: varchar(50)
    middle_name: varchar(50)
    last_name: varchar(50)
    email: varchar(50)
    password: varchar(50)
    section_id: integer

    # Pending, Active
    is_active: boolean

    email_token: varchar(50)

  indexes:
    type:
      fields: [type]
    first_name:
      fields: [first_name]
    middle_name:
      fields: [middle_name]
    last_name:
      fields: [last_name]
    email:
      fields: [email]
    email_token:
      fields: [email_token]
    is_active:
      fields: [is_active]

  relations:
    Section:
      local: section_id
      foreignAlias: id
      alias: section

  actAs:
    - Timestampable