Subject:
  tableName: 'subjects'
  columns: 
    name: string(50)
    profile_id: integer
    section_id: integer

  indexes:
    name: 
      fields: [name]

  relations:
    Profile: 
      alias: profile
      foreignAlias: subject
    Section: 
      alias: section
      foreignAlias: subjects

  actAs:
    - Timestampable
